branch-defaults:
  master:
    environment: Default-Environment
deploy:
  artifact: ../Archive.zip
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Docker 1.6.2
  default_region: us-west-2
  profile: eb-cli
  sc: git
